import os
import json
import tempfile
import subprocess
from datetime import datetime
from typing import Any, Dict


def run_scan(repo_path: str) -> Dict[str, Any]:
    """Run Bandit security scan on Python repository"""
    print("[Bandit] Starting security scan")
    if not os.path.exists(repo_path):
        return {
            "success": False,
            "error": "Repository path not found",
            "total_issues": 0,
            "severity_counts": {"high": 0, "medium": 0, "low": 0},
            "issues": [],
        }

    try:
        output_file = os.path.join(
            tempfile.gettempdir(), f"bandit_{datetime.now().timestamp()}.json"
        )

        subprocess.run(
            ["bandit", "-r", repo_path, "-f", "json", "-o", output_file, "-ll"],
            capture_output=True,
            text=True,
            timeout=120,
        )

        if os.path.exists(output_file):
            with open(output_file, "r") as f:
                bandit_data = json.load(f)
            os.remove(output_file)

            issues = bandit_data.get("results", [])
            metrics = bandit_data.get("metrics", {})

            severity_counts = {"high": 0, "medium": 0, "low": 0}
            detailed_issues = []

            confidence_map = {"HIGH": "high", "MEDIUM": "medium", "LOW": "low"}

            for issue in issues:
                severity = confidence_map.get(issue.get("issue_severity", "LOW").upper(), "low")
                confidence = confidence_map.get(issue.get("issue_confidence", "LOW").upper(), "low")

                severity_counts[severity] += 1

                detailed_issues.append(
                    {
                        "title": issue.get("issue_text", "Unknown"),
                        "severity": severity,
                        "confidence": confidence,
                        "file": issue.get("filename", "Unknown"),
                        "line_number": issue.get("line_number", 0),
                        "test_id": issue.get("test_id", ""),
                        "test_name": issue.get("test_name", ""),
                        "cwe": issue.get("issue_cwe", {}).get("id")
                        if isinstance(issue.get("issue_cwe"), dict)
                        else 0,
                    }
                )

            severity_order = {"high": 0, "medium": 1, "low": 2}
            detailed_issues.sort(key=lambda x: severity_order.get(x["severity"], 3))

            total_lines = sum(m.get("loc", 0) for m in metrics.values() if isinstance(m, dict))

            result = {
                "success": len(issues) == 0,
                "total_issues": len(issues),
                "severity_counts": severity_counts,
                "total_lines_scanned": total_lines,
                "issues": detailed_issues,
            }
            print("[Bandit] Scan complete")
            return result
        else:
            print("[Bandit] No output generated by bandit")
            return {
                "success": False,
                "error": "Bandit did not generate output",
                "total_issues": 0,
                "severity_counts": {"high": 0, "medium": 0, "low": 0},
                "issues": [],
            }

    except subprocess.TimeoutExpired:
        print("[Bandit] Scanner timeout")
        return {
            "success": False,
            "error": "Scanner timeout",
            "total_issues": 0,
            "severity_counts": {"high": 0, "medium": 0, "low": 0},
            "issues": [],
        }
    except FileNotFoundError:
        print("[Bandit] Bandit not installed")
        return {
            "success": False,
            "error": "Bandit not installed",
            "total_issues": 0,
            "severity_counts": {"high": 0, "medium": 0, "low": 0},
            "issues": [],
        }
    except Exception as e:
        print(f"[Bandit] Error: {str(e)}")
        return {
            "success": False,
            "error": str(e),
            "total_issues": 0,
            "severity_counts": {"high": 0, "medium": 0, "low": 0},
            "issues": [],
        }
